services:
  vytaan-submissions:
    build:
      context: .
      target: production
    ports:
      - "2000:2000"
    env_file:
      - .env
    environment:
      - PORT=0.0.0.0:2000
      - NODE_ENV=production
    volumes:
      - sqlite-data:/data
    restart: unless-stopped

volumes:
  sqlite-data:
